name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [frontend, backend]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd ${{ matrix.project }}
          npm ci
      - name: Run lint
        run: |
          cd ${{ matrix.project }}
          npm run lint || true
      - name: Run build
        run: |
          cd ${{ matrix.project }}
          npm run build
      - name: Run test
        run: |
          cd ${{ matrix.project }}
          npm test

  frontend-start:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Start frontend
        run: cd frontend && npm start &
        env:
          CI: true
      - name: Wait for frontend
        run: sleep 10

  backend-start:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: cd backend && npm ci
      - name: Start backend
        run: cd backend && npm run dev &
        env:
          CI: true
      - name: Wait for backend
        run: sleep 10